### PR TITLE
Toggle border styling on EmailX ad off for numeric layout

### PR DESCRIPTION
**Pull request by Shinsina**
Screen Shot 2021-07-20 at 8 12 50 AM
Screen Shot 2021-07-20 at 8 13 05 AM

### CODE REVIEW

**Comment by Shinsina** [comment]
[Make Email X placements for bottom NL banner](https://trello.com/c/wd3O7zYJ/42-make-email-x-placements-for-bottom-nl-banner)

**Comment by Shinsina** [comment]
Depending on the reply from the attached Trello card pull either this or https://github.com/parameter1/pmmi-media-group-newsletters/pull/41

**Review by brandonbk — CHANGES_REQUESTED** [review]
@Shinsina - names of specific numeric newsletters shouldn't be included in a low-level component.  If we ever add another numeric newsletter down the road, we would not know to go add it here.

Instead, I would suggest something like the following within the emailx component:
```
$ const topBorderStyle = {
  "border-top": "1px solid #cdcdcd",
  "padding-top": "20px",
  ...input.topBorderStyle,
};
```

Then, within the numeric template, around line 90: `top-border-style={ "border-top": "none", "padding-top": "0" }`

You would need to verify what padding-top should need to be set to.

This change will then apply to all numeric templates, both now and in the future.

**Review by brandonbk — CHANGES_REQUESTED** [review]
@Shinsina - Line 7 needs to be removed; it would likely cause a lint error since numericNewsletters is no longer being used.

Also, this branch is in conflict with master; that would need to be resolved before it can be approved and merged.

**Comment by jwade1327** [comment]
@brandonbk per Bea, we only need to remove the styling for the numeric template (not both) so these changes would need to be replaced for my initial pr "remove styling from bottom banner"

**Review by brandonbk — APPROVED** [review]

**Pull request merged**
